apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: bookstore-api
spec:
  type: NodePort
  selector:
    app: orders-service
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30004
