apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: bookstore-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: registry.gitlab.com/st1611/backend/orders-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
              protocol: TCP
