apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bookstore-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: registry.gitlab.com/st1611/backend/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              protocol: TCP
