apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bookstore-api
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
