apiVersion: v1
kind: Service
metadata:
  name: emails-service
  namespace: bookstore-api
spec:
  type: NodePort
  selector:
    app: emails-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30003
