apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service
  namespace: bookstore-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: book-service
          image: registry.gitlab.com/st1611/backend/books-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
