service: emails-service

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: '20201221'
  runtime: python3.8
  timeout: 60
  vpc:
    securityGroupIds:
      - ${env:lambda_security_group_id}
    subnetIds:
      - ${env:aws_private_subnet_01}
      - ${env:aws_private_subnet_02}

functions:
  api:
    handler: main.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: 
            origin: "*"
          authorizer:
            arn: ${env:AWS_COGNITO_ARN}

plugins:
  - serverless-python-requirements
  - serverless-offline
